name: Publish to GitHub Pages

on:
  [push]

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - run: npm install
      - name: Build for prod
        run: npm run build-prod
        env:
          REPO_URL: https://github.com/ericvalois/stats-car-workshop
          WEB_PATH_PREFIX: /
          WEB_ROOT_URL: https://ericvalois.com/stats-car-workshop
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
          external_repository: ericvalois/stats-car-workshop
          publish_branch: main

          